let blogs = [
  {
    id: 0,
    writer: "Ali Hassan",
    img: "./assets/images/testimonial-1.jpg",
    date: "11/10/2022",
    short:
      "We live in an era called the information age. New technology is emerging every day to make life simpler, more advanced and better for everyone.",
    long: "We live in an era called the information age. New technology is emerging every day to make life simpler, more advanced and better for everyone. The rate at which technology is evolving is almost exponential today. For business organisations, new technology helps to reduce costs, enhance customer experiences and increase profits.Nearly 50 billion devices will have internet connectivity by 2030. With the COVID-19 pandemic boosting businesses’ digital transformation journey, this goal is closer than anticipated. The familiarity with the latest IT technology holds the key to advancing your career and exploring new opportunities",
    category: "Fashion",
    title: "best shoes for mens in china",
    type: "new",
    poster: "assets/images/shoes-1.jpg",
  },
  {
    id: 1,
    writer: "Alena siraj",
    img: "./assets/images/testimonial-2.jpg",
    date: "09/10/2021",
    short:
      "Artificial Intelligence, also known as AI, started gaining popularity a decade ago. It has still not slowed down and continues to be one of the leading technologies in 2021.",
    long: "Artificial Intelligence, also known as AI, started gaining popularity a decade ago. It has still not slowed down and continues to be one of the leading technologies in 2021. AI is constantly evolving, and newer applications for this technology continue to spring upon the scene. Today’s most popular AI applications are image and speech recognition, navigation programs, voice assistants like Siri and Alexa, and much more.Organisations are looking to use AI to analyse customer and business interactions to derive insights and identify triggers. It will help them predict the demand for services such as hospitals or tourism and aid in the improvement of resource allocation for various projects.Machine Learning (ML) is a part of AI and uses supervised learning to learn new functions. It has seen a massive surge in demand for skilled professionals, making it an attractive trend to watch. According to Forrester, AI and Machine Learning will be responsible for 9% of all new jobs in the US by 2025.",
    category: "technology",
    title: "Artificial inteligence",
    type: "new",
    poster: "assets/images/pdcast.jpg",
  },
  {
    id: 2,
    writer: "Ahmad Nazir",
    img: "./assets/images/profile-1.jpg",
    date: "11/10/2021",
    short:
      "To help, The Get has gathered a robust list of our favorite, most versatile pieces we consider to be foundational for any closet",
    long: "To help, The Get has gathered a robust list of our favorite, most versatile pieces we consider to be foundational for any closet. Pared-back but never boring, these are the wardrobe essentials our editors find themselves turning to season after season, those mainstay items we look forward to wearing with everything for what’s left of 2022 and beyond. And while we’ll still welcome irresistible seasonal and trend-forward pieces like suit vests and sleek leather midi skirts—it’s fashion we’re obsessed with, after all!—we know those need to live alongside a capsule of staple items because every wardrobe needs a yin-yang balance. That shiny new statement item will dazzle even more when paired with, say, the perfect go-to denim.Ahead is a well-curated edit that has helped craft the foundation of our wardrobes. It’s safe to say we’re wearing at least one, if not more, of the highlighted pieces below daily. We’ve covered the classics: white t-shirts, crewneck sweaters, trench coats, tailored trousers, chic sneakers. And also those items that have more recently earned their spot as a wardrobe essential: ballet flats, knit dresses, menswear-inspired loafers, and sleeveless sweaters. These pieces have transcended their stance as a fleeting trend, becoming notable additions to the list.",
    category: "Fashion",
    title: "Best shoes wearing in china",
    type: "new",
    poster: "assets/images/shoes-3.jpg",
  },

  {
    id: 3,
    writer: "Ali asgar",
    img: "./assets/images/testimonial-1.jpg",
    date: "11/10/2022",
    short:
      "When we convert parts of our lives into software and devices through data, we are going through datafication.",
    long: "When we convert parts of our lives into software and devices through data, we are going through datafication. In this process, data-driven technology takes over human chores and tasks. Smartphones, office applications, industrial machines and even AI devices, all use data to interact with us and improve our lifestyles. Data has been a part of our lives for longer than you can even imagine. Storing this data requires security, which has led to an increase in the demand for data security specialisations in our country. IT professionals, data professionals, engineers, managers, technicians, all work in the same field. Careers in the data field require more skill than high-level qualifications. These skills can be acquired by doing some courses that teach you how the world of data works.",
    category: "technology",
    title: "Datafication",
    type: "new",
    poster: "assets/images/quantum-computing.jpg",
  },
  {
    id: 4,
    writer: "Ali Hassan",
    img: "./assets/images/testimonial-1.jpg",
    date: "11/10/2022",
    short:
      "We live in an era called the information age. New technology is emerging every day to make life simpler, more advanced and better for everyone.",
    long: "We live in an era called the information age. New technology is emerging every day to make life simpler, more advanced and better for everyone. The rate at which technology is evolving is almost exponential today. For business organisations, new technology helps to reduce costs, enhance customer experiences and increase profits.Nearly 50 billion devices will have internet connectivity by 2030. With the COVID-19 pandemic boosting businesses’ digital transformation journey, this goal is closer than anticipated. The familiarity with the latest IT technology holds the key to advancing your career and exploring new opportunities",
    category: "technology",
    type: "new",
    title: "Designing in computer ",
    poster: "assets/images/system-setup.jpg",
  },
  {
    id: 5,
    writer: "Ali asgar",
    img: "./assets/images/testimonial-1.jpg",
    date: "11/10/2022",
    short:
      "When we convert parts of our lives into software and devices through data, we are going through datafication.",
    long: "When we convert parts of our lives into software and devices through data, we are going through datafication. In this process, data-driven technology takes over human chores and tasks. Smartphones, office applications, industrial machines and even AI devices, all use data to interact with us and improve our lifestyles. Data has been a part of our lives for longer than you can even imagine. Storing this data requires security, which has led to an increase in the demand for data security specialisations in our country. IT professionals, data professionals, engineers, managers, technicians, all work in the same field. Careers in the data field require more skill than high-level qualifications. These skills can be acquired by doing some courses that teach you how the world of data works.",
    category: "food",
    title: "Datafication",
    type: "new",
    poster: "assets/images/food-3.jpg",
  },

  {
    id: 7,
    writer: "DR Amna Altaf",
    img: "./assets/images/profile-1.jpg",
    date: "11/10/2021",
    short:
      "To help, The Get has gathered a robust list of our favorite, most versatile pieces we consider to be foundational for any closet",
    long: "To help, The Get has gathered a robust list of our favorite, most versatile pieces we consider to be foundational for any closet. Pared-back but never boring, these are the wardrobe essentials our editors find themselves turning to season after season, those mainstay items we look forward to wearing with everything for what’s left of 2022 and beyond. And while we’ll still welcome irresistible seasonal and trend-forward pieces like suit vests and sleek leather midi skirts—it’s fashion we’re obsessed with, after all!—we know those need to live alongside a capsule of staple items because every wardrobe needs a yin-yang balance. That shiny new statement item will dazzle even more when paired with, say, the perfect go-to denim.Ahead is a well-curated edit that has helped craft the foundation of our wardrobes. It’s safe to say we’re wearing at least one, if not more, of the highlighted pieces below daily. We’ve covered the classics: white t-shirts, crewneck sweaters, trench coats, tailored trousers, chic sneakers. And also those items that have more recently earned their spot as a wardrobe essential: ballet flats, knit dresses, menswear-inspired loafers, and sleeveless sweaters. These pieces have transcended their stance as a fleeting trend, becoming notable additions to the list.",
    category: "nature",
    title: "Childern learn from parents",
    type: "new",
    poster: "assets/images/child.jpg",
  },

  {
    id: 8,
    writer: "Ali Hassan",
    img: "./assets/images/testimonial-1.jpg",
    date: "11/10/2022",
    short:
      "Robotic Process Automation (RPA) uses multiple software and applications to automate business processes such as data collection and analysis,",
    long: "Robotic Process Automation (RPA) uses multiple software and applications to automate business processes such as data collection and analysis, customer service and other repetitive tasks managed previously through manual processes.Like AI and Machine Learning, RPA is a rapidly advancing technology that automates many jobs across different industries. McKinsey has analysed that fewer than 5% of jobs today can be entirely automated, but nearly 60% can be automated at least partially.RPA offers several new career options and trajectories such as a programmer, project manager, business analyst or consultant. It also opens doors to high-paying jobs with a moderate learning curve in leading organisations. Choosing this technology as a career move can profit you immensely.",
    category: "technology",
    title: "3D printing in china",
    type: "new",
    poster: "assets/images/8.jpg",
  },
  {
    id: 9,
    writer: "Shazia qadri",
    img: "./assets/images/testimonial-2.jpg",
    date: "11/10/2022",
    short:
      "We live in an era called the information age. New technology is emerging every day to make life simpler, more advanced ",
    long: "We live in an era called the information age. New technology is emerging every day to make life simpler, more advanced and better for everyone. The rate at which technology is evolving is almost exponential today. For business organisations, new technology helps to reduce costs, enhance customer experiences and increase profits.Nearly 50 billion devices will have internet connectivity by 2030. With the COVID-19 pandemic boosting businesses’ digital transformation journey, this goal is closer than anticipated. The familiarity with the latest IT technology holds the key to advancing your career and exploring new opportunities",
    category: "technology",
    title: "rol of technology in modren era",
    poster: "assets/images/7.jpg",
    type: "featured",
  },
  {
    id: 10,
    writer: "Ali Hassan",
    img: "./assets/images/testimonial-1.jpg",
    date: "11/10/2022",
    short:
      "We live in an era called the information age. New technology is emerging every day to make life simpler, more advanced and better for everyone.",
    long: "We live in an era called the information age. New technology is emerging every day to make life simpler, more advanced and better for everyone. The rate at which technology is evolving is almost exponential today. For business organisations, new technology helps to reduce costs, enhance customer experiences and increase profits.Nearly 50 billion devices will have internet connectivity by 2030. With the COVID-19 pandemic boosting businesses’ digital transformation journey, this goal is closer than anticipated. The familiarity with the latest IT technology holds the key to advancing your career and exploring new opportunities",
    category: "technology",
    title: "Cyber security globalization",
    type: "new",
    poster: "assets/images/4.jpg",
  },
  {
    id: 11,
    writer: "Alena siraj",
    img: "./assets/images/testimonial-2.jpg",
    date: "09/10/2021",
    short:
      "Artificial Intelligence, also known as AI, started gaining popularity a decade ago. It has still not slowed down and continues to be one of the leading technologies in 2021.",
    long: "Artificial Intelligence, also known as AI, started gaining popularity a decade ago. It has still not slowed down and continues to be one of the leading technologies in 2021. AI is constantly evolving, and newer applications for this technology continue to spring upon the scene. Today’s most popular AI applications are image and speech recognition, navigation programs, voice assistants like Siri and Alexa, and much more.Organisations are looking to use AI to analyse customer and business interactions to derive insights and identify triggers. It will help them predict the demand for services such as hospitals or tourism and aid in the improvement of resource allocation for various projects.Machine Learning (ML) is a part of AI and uses supervised learning to learn new functions. It has seen a massive surge in demand for skilled professionals, making it an attractive trend to watch. According to Forrester, AI and Machine Learning will be responsible for 9% of all new jobs in the US by 2025.",
    category: "places",
    title: "Best hoteling services ",
    type: "featured",
    poster: "assets/images/hotel-1.jpg",
  },
  {
    id: 12,
    writer: "Demorio olvera",
    img: "./assets/images/testimonial-1.jpg",
    date: "11/10/2022",
    short:
      "Robotic Process Automation (RPA) uses multiple software and applications to automate business processes such as data collection and analysis,",
    long: "Robotic Process Automation (RPA) uses multiple software and applications to automate business processes such as data collection and analysis, customer service and other repetitive tasks managed previously through manual processes.Like AI and Machine Learning, RPA is a rapidly advancing technology that automates many jobs across different industries. McKinsey has analysed that fewer than 5% of jobs today can be entirely automated, but nearly 60% can be automated at least partially.RPA offers several new career options and trajectories such as a programmer, project manager, business analyst or consultant. It also opens doors to high-paying jobs with a moderate learning curve in leading organisations. Choosing this technology as a career move can profit you immensely.",
    category: "technology",
    title: "Artificial inteligence",
    type: "new",
    poster: "assets/images/developers.jpg",
  },
  // kk
  {
    id: 13,
    writer: "Ali Hassan",
    img: "./assets/images/testimonial-1.jpg",
    date: "11/10/2022",
    short:
      "Robotic Process Automation (RPA) uses multiple software and applications to automate business processes such as data collection and analysis,",
    long: "Robotic Process Automation (RPA) uses multiple software and applications to automate business processes such as data collection and analysis, customer service and other repetitive tasks managed previously through manual processes.Like AI and Machine Learning, RPA is a rapidly advancing technology that automates many jobs across different industries. McKinsey has analysed that fewer than 5% of jobs today can be entirely automated, but nearly 60% can be automated at least partially.RPA offers several new career options and trajectories such as a programmer, project manager, business analyst or consultant. It also opens doors to high-paying jobs with a moderate learning curve in leading organisations. Choosing this technology as a career move can profit you immensely.",
    category: "technology",
    title: "robotic Process Automation (RPA)",
    type: "new",
    poster: "assets/images/robotic-process.jpg",
  },
  {
    id: 14,
    writer: "mbappe martin",
    img: "./assets/images/testimonial-3.jpg",
    date: "11/10/2020",
    short:
      "Blockchain was popularised in the context of cryptocurrency and Bitcoin and the security it provides.",
    long: "Blockchain was popularised in the context of cryptocurrency and Bitcoin and the security it provides. However, it offers security that can be useful in several other ways as well. Blockchain can be defined as data that you can only add to, not take away or alter. It results in many sections of data which form a ‘chain’, hence the name Blockchain.The fact that existing data cannot be altered or removed makes Blockchain a highly secure technology. Blockchains are consensus-driven, which means no single person or organisation can take control of the data. There is no need for a third party to oversee transactions.As more industries adopt and implement blockchains, the demand for skilled blockchain developers has also increased. It requires the hands-on experience of programming languages, basic knowledge of OOPS, flat and relational databases, data structures, networking and web application development.",
    category: "technology",
    title: "Blockchain",
    type: "new",
    poster: "assets/images/developers.jpg",
  },
  {
    id: 15,
    writer: "Ahmad Nazir",
    img: "./assets/images/profile-1.jpg",
    date: "11/10/2021",
    short:
      "Today, millions of data points are collecting user information from various sources such as social media, websites,",
    long: "Today, millions of data points are collecting user information from various sources such as social media, websites, emails, and web searches. As the amount of data collected increases exponentially, other technologies like cloud computing fall short in several situations.Till a decade back, Cloud Computing was one of the fastest-growing technologies. However, it has become fairly mainstream, with the market dominated by major players such as Amazon Web Services (AWS), Microsoft Azure and Google Cloud Platform.As more organisations adopted Cloud Computing, they found several limitations in the technology. Edge Computing helps to bypass the latency that Cloud Computing causes and helps organisations to get data into a data centre for processing. It can exist ‘on edge’, in the sense that it is closer to where the data processing will ultimately take place. Edge Computing is used to process time-sensitive data in far-off locations with limited or no connectivity.Edge Computing application will keep growing as IoT devices increase. Its market share is set to reach $6.72 billion by 2022.",
    category: "food",
    title: "good food good life",
    type: "featured",
    poster: "assets/images/food-3.jpg",
  },

  {
    id: 17,
    writer: "Aslam athar",
    img: "./assets/images/testimonial-3.jpg",
    date: "11/10/2020",
    short:
      "Blockchain was popularised in the context of cryptocurrency and Bitcoin and the security it provides.",
    long: "Blockchain was popularised in the context of cryptocurrency and Bitcoin and the security it provides. However, it offers security that can be useful in several other ways as well. Blockchain can be defined as data that you can only add to, not take away or alter. It results in many sections of data which form a ‘chain’, hence the name Blockchain.The fact that existing data cannot be altered or removed makes Blockchain a highly secure technology. Blockchains are consensus-driven, which means no single person or organisation can take control of the data. There is no need for a third party to oversee transactions.As more industries adopt and implement blockchains, the demand for skilled blockchain developers has also increased. It requires the hands-on experience of programming languages, basic knowledge of OOPS, flat and relational databases, data structures, networking and web application development.",
    category: "technology",
    title: "Web designing ",
    type: "new",
    poster: "assets/images/tools-1.jpg",
  },

  {
    id: 20,
    writer: "Aleena siraj",
    img: "./assets/images/testimonial-2.jpg",
    date: "11/09/2022",
    short:
      "Quantum Computing is a typee of computing that focuses on developing computer technology based on the principles of quantum theory. ",
    long: "Quantum Computing is a typee of computing that focuses on developing computer technology based on the principles of quantum theory. This theory explains the behaviour of energy and materials on atomic and subatomic levels. In other words, it performs calculations based on the probability of an object’s state before measurement instead of just 0’s and 1’s.Quantum Computing can easily query, analyse and take action based on given data, regardless of the source. It played a major role in preventing COVID-19 and developing new vaccines. These computers are exponentially faster than normal computers. The revenue for the Quantum Computing market is projected to cross $2.5 billion by 2029.You need experience with quantum mechanics, linear algebra, machine learning, and information theory to enter this field.",
    category: "technology",
    title: "Quantum Computing",
    type: "new",
    poster: "assets/images/ai-1.jpg",
  },
  {
    id: 21,
    writer: "sana yaseen",
    img: "./assets/images/testimonial-2.jpg",
    date: "09/10/2021",
    short:
      "VR and AR have been popular for almost a decade now. Virtual Reality immerses the user into a new environment,",
    long: "VR and AR have been popular for almost a decade now. Virtual Reality immerses the user into a new environment, while Augmented Reality enhances the user’s existing environment. While their applications so far have been majorly linked with gaming and filters on social media, simulation software such as Virtual Ship is also used to train the US Navy, Army and Coast Guard ship captains.A whopping 14 million AR and VR devices were sold in 2019. The global market for this trending technology is predicted to reach $209.2 billion by 2022, which means more job opportunities for professionals in this field.By 2022, AR and VR are expected to integrate into our everyday lives much more deeply than today. They have huge potential and possible applications in training, entertainment, education, marketing and therapy or post-injury rehabilitation. It is also widely used by advertisers and brands to create new immersive experiences for their customers.Starting a career in VR or AR doesn’t require too much specialisation. Basic programming skills and a forward-thinking mindset coupled with optics as a skill set can help you easily secure a job in this field.",
    category: "technology",
    title: "Virtual Reality Augmented Reality",
    type: "new",
    poster: "assets/images/2.jpg",
  },
  {
    id: 22,
    writer: "Danish Riaz",
    img: "./assets/images/testimonial-3.jpg",
    date: "11/10/2020",
    short:
      "Blockchain was popularised in the context of cryptocurrency and Bitcoin and the security it provides.",
    long: "Blockchain was popularised in the context of cryptocurrency and Bitcoin and the security it provides. However, it offers security that can be useful in several other ways as well. Blockchain can be defined as data that you can only add to, not take away or alter. It results in many sections of data which form a ‘chain’, hence the name Blockchain.The fact that existing data cannot be altered or removed makes Blockchain a highly secure technology. Blockchains are consensus-driven, which means no single person or organisation can take control of the data. There is no need for a third party to oversee transactions.As more industries adopt and implement blockchains, the demand for skilled blockchain developers has also increased. It requires the hands-on experience of programming languages, basic knowledge of OOPS, flat and relational databases, data structures, networking and web application development.",
    category: "technology",
    title: "Technological world india",
    type: "new",
    poster: "assets/images/developers-2.jpg",
  },

  {
    id: 24,
    writer: "Yumna zaidi",
    img: "./assets/images/testimonial-2.jpg",
    date: "11/09/2022",
    short:
      "Quantum Computing is a typee of computing that focuses on developing computer technology based on the principles of quantum theory. ",
    long: "Quantum Computing is a typee of computing that focuses on developing computer technology based on the principles of quantum theory. This theory explains the behaviour of energy and materials on atomic and subatomic levels. In other words, it performs calculations based on the probability of an object’s state before measurement instead of just 0’s and 1’s.Quantum Computing can easily query, analyse and take action based on given data, regardless of the source. It played a major role in preventing COVID-19 and developing new vaccines. These computers are exponentially faster than normal computers. The revenue for the Quantum Computing market is projected to cross $2.5 billion by 2029.You need experience with quantum mechanics, linear algebra, machine learning, and information theory to enter this field.",
    category: "food",
    title: "Famouse chins foods in asia ",
    type: "new",
    poster: "assets/images/food-1.jpg",
  },

  {
    id: 25,
    writer: "sana yaseen",
    img: "./assets/images/testimonial-2.jpg",
    date: "09/10/2021",
    short:
      "VR and AR have been popular for almost a decade now. Virtual Reality immerses the user into a new environment,",
    long: "VR and AR have been popular for almost a decade now. Virtual Reality immerses the user into a new environment, while Augmented Reality enhances the user’s existing environment. While their applications so far have been majorly linked with gaming and filters on social media, simulation software such as Virtual Ship is also used to train the US Navy, Army and Coast Guard ship captains.A whopping 14 million AR and VR devices were sold in 2019. The global market for this trending technology is predicted to reach $209.2 billion by 2022, which means more job opportunities for professionals in this field.By 2022, AR and VR are expected to integrate into our everyday lives much more deeply than today. They have huge potential and possible applications in training, entertainment, education, marketing and therapy or post-injury rehabilitation. It is also widely used by advertisers and brands to create new immersive experiences for their customers.Starting a career in VR or AR doesn’t require too much specialisation. Basic programming skills and a forward-thinking mindset coupled with optics as a skill set can help you easily secure a job in this field.",
    category: "technology",
    title: "Virtual Reality Augmented Reality",
    type: "new",
    poster: "assets/images/1.jpg",
  },
  {
    id: 26,
    writer: "Danish Riaz",
    img: "./assets/images/testimonial-3.jpg",
    date: "11/10/2020",
    short:
      "Blockchain was popularised in the context of cryptocurrency and Bitcoin and the security it provides.",
    long: "Blockchain was popularised in the context of cryptocurrency and Bitcoin and the security it provides. However, it offers security that can be useful in several other ways as well. Blockchain can be defined as data that you can only add to, not take away or alter. It results in many sections of data which form a ‘chain’, hence the name Blockchain.The fact that existing data cannot be altered or removed makes Blockchain a highly secure technology. Blockchains are consensus-driven, which means no single person or organisation can take control of the data. There is no need for a third party to oversee transactions.As more industries adopt and implement blockchains, the demand for skilled blockchain developers has also increased. It requires the hands-on experience of programming languages, basic knowledge of OOPS, flat and relational databases, data structures, networking and web application development.",
    category: "technology",
    title: "Blockchain",
    type: "featured",
    poster: "assets/images/developers-2.jpg",
  },
  {
    id: 27,
    writer: "Asad nadeem",
    img: "./assets/images/profile-1.jpg",
    date: "11/10/2021",
    short:
      "It is one of the most promising technologies of the decade. Multiple devices or ‘things’ ",
    long: "It is one of the most promising technologies of the decade. Multiple devices or ‘things’ today are wifi-enabled, which means they can be connected to the internet. The Internet of Things is a network of diverse connected devices. Devices within the network can communicate with each other, collect data and transfer it across the network without human intervention.There are hundreds of real-life Internet of Things (IoT) applications - from tracking activity using smart devices that connect to your phone, to remotely monitoring home doors or switching applications on and off. Businesses also use IoT for many things like monitoring activity in remote locations from a central hub and predicting when a device will malfunction so that corrective measures can be taken before it’s too late.It is predicted that by 2030, over 50 billion devices will be connected via the Internet of Things. Global spending on this technology will reach an estimated $1.1 trillion in the next two years. IoT is currently in its initial stages and will advance rapidly in the near future. It requires knowledge of AI and Machine Learning fundamentals, as well as information security and data analytics.Additional Read: How to Become a Certified Ethical Hacker (CEH)",
    category: "technology",
    title: "Internet of Things (IoT)",
    type: "new",
    poster: "assets/images/developers.jpg",
  },
  {
    id: 28,
    writer: "Asma saeed",
    img: "./assets/images/testimonial-2.jpg",
    date: "09/10/2021",
    short:
      "5G technology has the potential to change the way we see the online world. 3G and 4G technology transformed",
    long: "5G technology has the potential to change the way we see the online world. 3G and 4G technology transformed how we interacted with mobile devices, enabling faster internet browsing, using data-driven services, and increasing bandwidth for live streaming.5G aims to revolutionise our virtual interactions by integrating AR and VR technology and better cloud-based gaming experiences. It will also be used in factories and enterprises for monitoring and streamlining operations. 5G also has applications in road safety and rule implementation, smart grid control and smart retail experiences, in the form of live high-definition cameras.Telecom companies around the world are working on creating 5G-ready services and devices. The technology was announced and rolled out in select places in 2020, with a worldwide launch expected in 2022. The launch of 5G has been delayed for a while but is set to quickly reach the world and become a part of every person’s life.",
    category: "food",
    title: "5 best foods that famouse internationaly",
    type: "featured",
    poster: "assets/images/food-3.jpg",
  },
  {
    id: 29,
    writer: "DR RiazulAmin",
    img: "./assets/images/testimonial-3.jpg",
    date: "11/10/2022",
    short:
      "Since the dawn of computers, cybersecurity has played a major role in ensuring safer user experiences.",
    long: "Since the dawn of computers, cybersecurity has played a major role in ensuring safer user experiences. It is not a new trend, but given that technology is evolving rapidly, cybersecurity measures need to be constantly upgraded and improved. Threats and hacking attempts are growing in number and intensity, which calls for improving security protocols and strengthening systems against malicious attacks.Data is the most valuable asset today, and hackers are constantly trying to steal data or information. This is why cybersecurity will always be a trending technology and need to constantly evolve to stay ahead of hackers. Demand for cybersecurity professionals is growing three times faster than any other tech jobs today. More and more businesses realise its importance, resulting in businesses spending about $6 trillion on cybersecurity by 2022.Cybersecurity job roles transition from the ethical hacker to security engineer to Chief Security Officer. The pay is significantly more than in other technology job roles due to its significance in ensuring a secure user experience",
    category: "Marketing",
    title: "Ho to sell digitally",
    type: "popular",
    poster: "assets/images/marketing-1.jpg",
  },

  {
    id: 33,
    writer: "Asma saeed",
    img: "./assets/images/testimonial-2.jpg",
    date: "09/10/2021",
    short:
      "5G technology has the potential to change the way we see the online world. 3G and 4G technology transformed",
    long: "5G technology has the potential to change the way we see the online world. 3G and 4G technology transformed how we interacted with mobile devices, enabling faster internet browsing, using data-driven services, and increasing bandwidth for live streaming.5G aims to revolutionise our virtual interactions by integrating AR and VR technology and better cloud-based gaming experiences. It will also be used in factories and enterprises for monitoring and streamlining operations. 5G also has applications in road safety and rule implementation, smart grid control and smart retail experiences, in the form of live high-definition cameras.Telecom companies around the world are working on creating 5G-ready services and devices. The technology was announced and rolled out in select places in 2020, with a worldwide launch expected in 2022. The launch of 5G has been delayed for a while but is set to quickly reach the world and become a part of every person’s life.",
    category: "places",
    title: "5 best hotels in pakistan",
    type: "popular",
    poster: "assets/images/hotel-1.jpg",
  },
  {
    id: 34,
    writer: "DR RiazulAmin",
    img: "./assets/images/testimonial-3.jpg",
    date: "11/10/2022",
    short:
      "Since the dawn of computers, cybersecurity has played a major role in ensuring safer user experiences.",
    long: "Since the dawn of computers, cybersecurity has played a major role in ensuring safer user experiences. It is not a new trend, but given that technology is evolving rapidly, cybersecurity measures need to be constantly upgraded and improved. Threats and hacking attempts are growing in number and intensity, which calls for improving security protocols and strengthening systems against malicious attacks.Data is the most valuable asset today, and hackers are constantly trying to steal data or information. This is why cybersecurity will always be a trending technology and need to constantly evolve to stay ahead of hackers. Demand for cybersecurity professionals is growing three times faster than any other tech jobs today. More and more businesses realise its importance, resulting in businesses spending about $6 trillion on cybersecurity by 2022.Cybersecurity job roles transition from the ethical hacker to security engineer to Chief Security Officer. The pay is significantly more than in other technology job roles due to its significance in ensuring a secure user experience",
    category: "places",
    title: "5 best bank in pakistan",
    type: "popular",
    poster: "assets/images/banks.jpg",
  },

  {
    id: 38,
    writer: "Shahruh Khan",
    img: "./assets/images/testimonial-3.jpg",
    date: "11/10/2022",
    short:
      "Since the dawn of computers, cybersecurity has played a major role in ensuring safer user experiences.",
    long: "Since the dawn of computers, cybersecurity has played a major role in ensuring safer user experiences. It is not a new trend, but given that technology is evolving rapidly, cybersecurity measures need to be constantly upgraded and improved. Threats and hacking attempts are growing in number and intensity, which calls for improving security protocols and strengthening systems against malicious attacks.Data is the most valuable asset today, and hackers are constantly trying to steal data or information. This is why cybersecurity will always be a trending technology and need to constantly evolve to stay ahead of hackers. Demand for cybersecurity professionals is growing three times faster than any other tech jobs today. More and more businesses realise its importance, resulting in businesses spending about $6 trillion on cybersecurity by 2022.Cybersecurity job roles transition from the ethical hacker to security engineer to Chief Security Officer. The pay is significantly more than in other technology job roles due to its significance in ensuring a secure user experience",
    category: "Technology",
    title: "5G internet service in pakistan",
    type: "popular",
    poster: "assets/images/tchnology-1.jpg",
  },

  {
    id: 41,
    writer: "SAba Naz",
    img: "./assets/images/testimonial-2.jpg",
    date: "11/10/2021",
    short:
      "To help, The Get has gathered a robust list of our favorite, most versatile pieces we consider to be foundational for any closet",
    long: "To help, The Get has gathered a robust list of our favorite, most versatile pieces we consider to be foundational for any closet. Pared-back but never boring, these are the wardrobe essentials our editors find themselves turning to season after season, those mainstay items we look forward to wearing with everything for what’s left of 2022 and beyond. And while we’ll still welcome irresistible seasonal and trend-forward pieces like suit vests and sleek leather midi skirts—it’s fashion we’re obsessed with, after all!—we know those need to live alongside a capsule of staple items because every wardrobe needs a yin-yang balance. That shiny new statement item will dazzle even more when paired with, say, the perfect go-to denim.Ahead is a well-curated edit that has helped craft the foundation of our wardrobes. It’s safe to say we’re wearing at least one, if not more, of the highlighted pieces below daily. We’ve covered the classics: white t-shirts, crewneck sweaters, trench coats, tailored trousers, chic sneakers. And also those items that have more recently earned their spot as a wardrobe essential: ballet flats, knit dresses, menswear-inspired loafers, and sleeveless sweaters. These pieces have transcended their stance as a fleeting trend, becoming notable additions to the list.",
    category: "Fashion",
    title: "womens haire styles in uk",
    type: "popular",
    poster: "assets/images/womens-type.jpg",
  },

  {
    id: 43,
    writer: "Ahsan mugal",
    img: "./assets/images/testimonial-1.jpg",
    date: "11/10/2022",
    short:
      "This is one of the newest industry trends within the software domain to gain momentum.",
    long: "This is one of the newest industry trends within the software domain to gain momentum. It continues to rise as IoT becomes a more mainstream technology with diverse applications. Full stack development covers the front and back-end development of applications and websites.Organisations are working on developing more user-friendly and comprehensive apps for their target audience. For this, a full stack developer must have a deep understanding of server-side programming and web development. If you develop the skills needed to create a website, your services will always have a place in the industry. More and more businesses are moving to digital every day, increasing the demand for web developers and designers.",
    category: "technology",
    title: "best singing mics for better voice",
    type: "featured",
    poster: "assets/images/pdcast.jpg",
  },
  {
    id: 44,
    writer: "Humaira saeed",
    img: "./assets/images/testimonial-2.jpg",
    date: "11/10/2021",
    short:
      "To help, The Get has gathered a robust list of our favorite, most versatile pieces we consider to be foundational for any closet",
    long: "To help, The Get has gathered a robust list of our favorite, most versatile pieces we consider to be foundational for any closet. Pared-back but never boring, these are the wardrobe essentials our editors find themselves turning to season after season, those mainstay items we look forward to wearing with everything for what’s left of 2022 and beyond. And while we’ll still welcome irresistible seasonal and trend-forward pieces like suit vests and sleek leather midi skirts—it’s fashion we’re obsessed with, after all!—we know those need to live alongside a capsule of staple items because every wardrobe needs a yin-yang balance. That shiny new statement item will dazzle even more when paired with, say, the perfect go-to denim.Ahead is a well-curated edit that has helped craft the foundation of our wardrobes. It’s safe to say we’re wearing at least one, if not more, of the highlighted pieces below daily. We’ve covered the classics: white t-shirts, crewneck sweaters, trench coats, tailored trousers, chic sneakers. And also those items that have more recently earned their spot as a wardrobe essential: ballet flats, knit dresses, menswear-inspired loafers, and sleeveless sweaters. These pieces have transcended their stance as a fleeting trend, becoming notable additions to the list.",
    category: "Fashion",
    title: "Wardrobe items that see the most use.",
    type: "new",
    poster: "assets/images/10.jpg",
  },
  {
    id: 45,
    writer: "iftkhar takar",
    img: "./assets/images/testimonial-1.jpg",
    date: "11/10/2022",
    short:
      "This is one of the newest industry trends within the software domain to gain momentum.",
    long: "This is one of the newest industry trends within the software domain to gain momentum. It continues to rise as IoT becomes a more mainstream technology with diverse applications. Full stack development covers the front and back-end development of applications and websites.Organisations are working on developing more user-friendly and comprehensive apps for their target audience. For this, a full stack developer must have a deep understanding of server-side programming and web development. If you develop the skills needed to create a website, your services will always have a place in the industry. More and more businesses are moving to digital every day, increasing the demand for web developers and designers.",
    category: "fashion",
    title: "Best shoes for mens ",
    type: "featured",
    poster: "assets/images/shoes-1.jpg",
  },
  {
    id: 46,
    writer: "Ali Raza",
    img: "./assets/images/testimonial-1.jpg",
    date: "11/10/2022",
    short:
      "When we convert parts of our lives into software and devices through data, we are going through datafication.",
    long: "When we convert parts of our lives into software and devices through data, we are going through datafication. In this process, data-driven technology takes over human chores and tasks. Smartphones, office applications, industrial machines and even AI devices, all use data to interact with us and improve our lifestyles. Data has been a part of our lives for longer than you can even imagine. Storing this data requires security, which has led to an increase in the demand for data security specialisations in our country. IT professionals, data professionals, engineers, managers, technicians, all work in the same field. Careers in the data field require more skill than high-level qualifications. These skills can be acquired by doing some courses that teach you how the world of data works.",
    category: "technology",
    title: "3d printing in pakistan",
    type: "new",
    poster: "assets/images/9.jpg",
  },
  {
    id: 47,
    writer: "Ahmad Nazir",
    img: "./assets/images/profile-1.jpg",
    date: "11/10/2021",
    short:
      "To help, The Get has gathered a robust list of our favorite, most versatile pieces we consider to be foundational for any closet",
    long: "To help, The Get has gathered a robust list of our favorite, most versatile pieces we consider to be foundational for any closet. Pared-back but never boring, these are the wardrobe essentials our editors find themselves turning to season after season, those mainstay items we look forward to wearing with everything for what’s left of 2022 and beyond. And while we’ll still welcome irresistible seasonal and trend-forward pieces like suit vests and sleek leather midi skirts—it’s fashion we’re obsessed with, after all!—we know those need to live alongside a capsule of staple items because every wardrobe needs a yin-yang balance. That shiny new statement item will dazzle even more when paired with, say, the perfect go-to denim.Ahead is a well-curated edit that has helped craft the foundation of our wardrobes. It’s safe to say we’re wearing at least one, if not more, of the highlighted pieces below daily. We’ve covered the classics: white t-shirts, crewneck sweaters, trench coats, tailored trousers, chic sneakers. And also those items that have more recently earned their spot as a wardrobe essential: ballet flats, knit dresses, menswear-inspired loafers, and sleeveless sweaters. These pieces have transcended their stance as a fleeting trend, becoming notable additions to the list.",
    category: "Fashion",
    title: "Wardrobe items that see the most use.",
    type: "popular",
    poster: "assets/images/10.jpg",
  },

  {
    id: 48,
    writer: "Ali asgar",
    img: "./assets/images/testimonial-1.jpg",
    date: "11/10/2022",
    short:
      "When we convert parts of our lives into software and devices through data, we are going through datafication.",
    long: "When we convert parts of our lives into software and devices through data, we are going through datafication. In this process, data-driven technology takes over human chores and tasks. Smartphones, office applications, industrial machines and even AI devices, all use data to interact with us and improve our lifestyles. Data has been a part of our lives for longer than you can even imagine. Storing this data requires security, which has led to an increase in the demand for data security specialisations in our country. IT professionals, data professionals, engineers, managers, technicians, all work in the same field. Careers in the data field require more skill than high-level qualifications. These skills can be acquired by doing some courses that teach you how the world of data works.",
    category: "food",
    title: "best foods in dubai",
    type: "popular",
    poster: "assets/images/food-1.jpg",
  },
  {
    id: 49,
    writer: "Aqsa salman",
    img: "./assets/images/testimonial-2.jpg",
    date: "09/10/2021",
    short:
      "3D printing has become a key technology used to create prototypees, especially in the industrial and biomedical fields",
    long: "3D printing has become a key technology used to create prototypees, especially in the industrial and biomedical fields. 3D printers allow you to create a real object from a printer! Needless to say, this cost-effective innovation is here to stay. Brands and companies that work in the healthcare, data and industrial sectors need 3D printing of their products, which has boosted the requirement of people specialising in Machine learning, 3D printing, modelling and AI.",
    category: "technology",
    title: "3D printing has become a key technology",
    type: "popular",
    poster: "assets/images/8.jpg",
  },
  {
    id: 50,
    writer: "Danish Riaz",
    img: "./assets/images/testimonial-3.jpg",
    date: "11/10/2020",
    short:
      "The digital era has computerised every mobile device and application, firmly establishing computing power",
    long: "The digital era has computerised every mobile device and application, firmly establishing computing power in this generation. Data scientists have predicted that the infrastructure used to harness this computing power is only going to evolve in the coming years. Computing power is giving us advanced technology to make our lives better and is also creating more jobs in the tech industry. Fields like data science, data analytics, IT management, robotics, etc have the potential to create the largest percentage of employment in the country. Many international brands and companies hire from India because of the specialised training widely available in the country. The more computing our devices need, the more specialised professionals will be required and the economy will flourish as a result.",
    category: "technology",
    title: " Computing Power",
    type: "new",
    poster: "assets/images/developers.jpg",
  },
];
export { blogs };
